# Swagger配置
# springdoc-openapi项目配置
server:
  port: 8080
  servlet:
    context-path: /
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.aipaint
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

#百度翻译API配置
baidu:
  from: zh
  to: en
  appid: 20231109001875415
  key: Byb_ezl3pWADDT0WHAkZ

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aipaint?serverTimezone=GMT%2b8
    username: root
    password: 1234

#python后端相关信息
py:
  host: 127.0.0.1
  port: 8081
  text_request_method: text

#发送邮件相关配置
sender:
  email: m13138873239@163.com
  password: LVYXCRPWXKYJDTZS
mybatis:
  mapper-locations: classpath:mapper/**

#jedis配置
jedis:
  host: 127.0.0.1
  port: 6379

#jwt相关配置
jwt:
  secret: AbbeyRoad
  issuer: zhuang
  existHour: 2  #可以设置成永不过期的token